### ISSUE TITLE
if文

### ISSUE THREAD

**Issue by c0b21149** [c0b21047/ProjExD#6]
この場合はelif ではなくifでもいいのでは？
どっちが奇麗なのかはわかりかねるが打つ文字数が少なくはなる
https://github.com/c0b21047/ProjExD/blob/7ab11bf5bf2cb8d85abc7d382816d65d9ec4820d/ex03/maze.py#L24

**Comment by c0b21047** [comment]
確かに打つ文字は少なくなるけれども内部処理的にはelifのほうが処理数が少なくなります。（if文をいちいちチェックしないため）
